### ISSUE TITLE
Logged in users can execute arbitrary JavaScript

### ISSUE THREAD

**Issue by dnouri** [Kotti/Kotti#296]
What follows is a report of a XSS vulnerability in Kotti by Marco D:

I believe there's an XSS vulnerability in Kotti. If you go to the
demo and give a page the following title:

&lt;SCRIPT>alert("XSS");//<&lt;/SCRIPT>

It'll pop up an XSS alert when you try to edit the item.

To reproduce (http://kottidemo.danielnouri.org/):

1) Log in to the demo (say, as owner / qwerty)

2) Add a document

3) Give it the title: &lt;SCRIPT>alert("XSS");//&lt;/SCRIPT>

4) Save it

5) Try to Edit it. An "XSS" pop-up will appear.

It seems you have to be logged in, but I do believe sanitation
is being done so I presume Kotti does not in principle allow users
to write arbitrary scripts in their articles.

**Comment by tiberiuichim** [comment]
@disko: I think this modification should be done at render time. If it's configurable, the site administrators can change the configuration any time, but existing content cannot adapt to the changes, as they won't have those tags/attributes anymore.

**Comment by teixas** [comment]
How about using bleach? https://pypi.python.org/pypi/bleach

**Comment by disko** [comment]
Fixed / implemented via #408.
