### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by disko** [Kotti/Kotti#348]
Title says it all.

A quick check of `requirements.txt` with `caniusepython3` claims these dependencies needed to be Python 3 compatible first:
- js.jquery (which is blocking js.bootstrap)
- js.chosen
- js.jquery_form (which is blocking js.deform)
- js.jquery_maskedinput (which is blocking js.deform)
- js.jquery_maskmoney (which is blocking js.deform)
- js.jquery_sortable (which is blocking js.deform)
- js.jquery_timepicker_addon (which is blocking js.deform)
- js.jqueryui (which is blocking js.deform)
- js.modernizr (which is blocking js.deform)
- js.tinymce (which is blocking js.deform)
- js.fineuploader
- js.html5shiv
- js.jquery_tablednd
- js.jqueryui_tagit
- kotti_tinymce  
- plone.scale
- pytz
- repoze.zcml (which is blocking repoze.workflow)
- shutilwhich
- yurl

Some (most?) of them are false positives, because they do officially support Python 3 and are just lacking the corresponding trove classifiers.  All they `js.*` should work with no or very little modification.  `shutilwhich` is a Python 2 backport of a module from the Python 3 standard library.

This might change until we start working on this ourselves, but even if it won't and we'd need to add Python 3 support to some dependencies ourselves, this seems absolutely doable.

**Comment by mgrbyte** [comment]
@disko I've just re-checked these, somewhat laboriously, since caniusepython3 seems to fail with a MemoryError when checking kotti_tinymce.
(Ran with `caniusepython3 -r kotti-stable-requirements.txt` and `caniusepython3 -p kotti_tinymce`)

The following still need porting/classifiers amending:
  * bleach-whitelist
  * js.jquery (which is blocking js.bootstrap)
  * js.chosen (blocked by js.jquery)
  * js.deform (blocked by all the other js packages)
  * js.jquery_form (which is blocking js.deform)
  * js.jquery_maskedinput (which is blocking js.deform)
  * js.jquery_maskmoney (which is blocking js.deform)
  * js.jquery_sortable (which is blocking js.deform)
  * js.jquery_timepicker_addon (which is blocking js.deform)
  * js.jqueryui (which is blocking js.deform)
  * js.modernizr (which is blocking js.deform)
  * js.tinymce (which is blocking js.deform)
  * js.fineuploader
  * js.html5shiv
  * kotti_tinymce (? MerroyError during check)
  * plone.scale (Blocked by Persistence)
  * shutilwhich
  * usersettings

bleach-whitelist looks be a trivial case/port/might just work.
plone.scale might work on Python3  with the pure python implementation of Persistence (?)

**Comment by mgrbyte** [comment]
The cause of the MemoryError described above is `caniusepython3` doesn't handle recursive dependencies gracefully, and:
  Kotti depends on kotti_tinymce and kotti_tincymce depends on Kotti.

**Comment by disko** [comment]
This circular dependency is indeed something that really bugs me.  Actually ``Kotti`` doesn't really depend on ``kotti_tinymce``, it's just there because we want WYSIWYG editing out of the box.  Maybe we should drop it from the package's dependencies but leave it in ``requires.txt`` and ``app.ini`` / ``development.ini``?

Opinions?  (/cc @dnouri, @tiberiuichim)

**Comment by mgrbyte** [comment]
[Opened a PR here](https://github.com/brettcannon/caniusepython3/pull/90)

**Comment by disko** [comment]
``bleach-whitelist`` is only a collection of strings, the ``js.*`` packages just call functions / methods from ``fanstatic`` and pass them strings.  They all just need to use unicode literals instead of plain Python 2 strings and proper trove classifiers in their respective ``setup.py``.  

``usersettings`` is probably the same – it's a very simple package (just ~100 LOC) that determines where to store user settings on various OSs.  We use it to remember the last used answers to the questions asked during scaffolding. If it turned out not to be a simple fix, we could replace it with anything else or just drop it (at the sole cost of just losing some convenience).

``shutilwhich`` is a backport of ``shutil.which``from the Python 3 standard library, so there's no need to port it.

**Comment by mgrbyte** [comment]
I'm sure there was/is a reason `kotti_tinymce` is maintained as a separate package -
Assuming its not used outside of Kotti, could the package be 'inlined' into the kotti core as a regular sub-package?

**Comment by disko** [comment]
The idea is to let users chose which WYSIWYG editor to use (if any at all).  Currently there's only ``kotti_tinymce`` but there could be others, and probably should – nowadays much leaner solutions exist.  

I strongly oppose moving its code to the ``Kotti`` package.

**Comment by tiberiuichim** [comment]
If TinyMCE is just one of the possible choices, then I think we can remove it from Kotti's setup.py and place it in requirements.txt only.

Also, perhaps we can get rid of plone.scale as a dependency? The code is BSD and we're only using the scale.py module, a 160 lines module. Or maybe find some other generic package that does resizing based on Pillow.

**Comment by castaf** [comment]
+1

**Comment by disko** [comment]
On 20 Apr 2015, at 9:46, tiberiuichim wrote:

> If TinyMCE is just one of the possible choices, then I think we can 
> remove it from Kotti's setup.py and place it in requirements.txt only.

It is just a choice, despite being the only one ATM.

> Also, perhaps we can get rid of plone.scale as a dependency? The code 
> is BSD and we're only using the scale.py module, a 160 lines
> module. Or maybe find some other generic package that does resizing 
> based on Pillow.

w.r.t. Python 3 compatibility that might make sense. The code we 
actually use is even less: we only use the ``thumbnail`` resizing, which 
shouldn't be more than a few lines using only ``Pillow``.

**Comment by mgrbyte** [comment]
I have a branch that's a work in progress... ~40  test failures.
https://github.com/mgrbyte/Kotti/commit/3990a9750a4eff9683bd0d32c43ec3e8f162c3c6

**Comment by disko** [comment]
Wow, good job!

A few remarks and questions (partially also apply to your ``notfound`` branch):

 - yes, ``webtest`` is the way to go for new tests, so much less pain than the doctests.
 - what's the reason for using ``zope.interface.implementer`` instead of ``zope.interface.implements``?
 - "setup.cfg: configparser does not like %.min.[css,js] (kotti_tinymce, kotti)": FWIW, you can remove the ``[minify_*]`` sections as well as the ``minify`` alias and the ``minify`` in ``development_requires``.  For the few files we have, we can do minification manually – they hardly ever change at all.

**Comment by disko** [comment]
> I have a branch that's a work in progress... ~40 test failures.

Does that imply that you have Kotti running on Python 3 and "only" the tests are failing?

**Comment by mgrbyte** [comment]
Yep :)
`pshell development.ini` works
Need to test the UI, but it starts.
~40 test fail, most of the browser tests, some low hanging fruit (urllib imports, avoid using the unicode builtin)

**Comment by mgrbyte** [comment]
* `zope.interface.implementer` vs  `zope.interface.implements`
   * I think its the modern way to spell it
  * I prefer the syntax over the class body solution.
  * There's a deeper technical reason for my preference to do with the implementation, one day the use of the `sys..getframe` hack may be removed .
* minify - good to know! this needs doing in kotti_tinymce too

**Comment by mgrbyte** [comment]
@disko Does Kotti need to support Python 2.6 going forward?
It would make this much easier if it didn't.

I think converting the doc-tests to `webtest` tests would be good thing to do.
Had I done that first, I think it might have make this porting exercise easier, not sure about doing that now since I'd like to get this "done" before any potential major change comes in (avoid merge hell)

**Comment by disko** [comment]
On 29 Sep 2015, at 11:31, Matt Russell wrote:

> Yep :)
> `pshell development.ini` works

Impressive!

> Need to test the UI, but it starts.

My feeling is, that the UI should be rather unproblematic.

> ~40 test fail, most of the browser tests, some low hanging fruit 
> (urllib imports, avoid using the unicode builtin)

I find browser tests to be a PITA.  Webtest is so much nicer, especially 
w.r.t. test setup as you can use pytest's fixtures with them.

**Comment by disko** [comment]
On 29 Sep 2015, at 11:35, Matt Russell wrote:

> * minify - good to know! this needs doing in kotti_tinymce too

Done: 
https://github.com/Kotti/kotti_tinymce/commit/3f99922db6ea368bb261b1fa758d56de0eaf7d31.

It's not used there anymore.  The whole static resource management and 
bundling was migrated to npm, bower and gulp.

**Comment by disko** [comment]
On 29 Sep 2015, at 11:40, Matt Russell wrote:

> @disko Does Kotti need to support Python 2.6 going forward?

FWIW: no.  @dnouri, @tiberiuichim, or anybody else: do you need (or 
think someone needs) 2.6 support?

**Comment by tiberiuichim** [comment]
No need for python 2.6 on my side

**Comment by mgrbyte** [comment]
Down to 1 real failing test now.
7 others, which are browser*.txt tests, or those that otherwise depend on `wsgi_intercept.zope_testbrowser` (TestUploadFile)

* TestNode.test_root_acl, Ordering of lists is different, kotti.tests.test_node:15

I've tested in the UI, and everything seems to work (login, logout, add user, saving, sharing et al)

**Comment by dnouri** [comment]
I'm also fine with dropping Python 2.6 support.  Awesome work, by the way!

**Comment by disko** [comment]
So let's do it: drop Python 2.6 and let's have Python 3 instead.

**Comment by disko** [comment]
DONE :)
