### ISSUE TITLE
kotti.use_workflow

### ISSUE THREAD

**Issue by davidemoro** [Kotti/Kotti#395]
If you override the custom workflow provided by Kotti:
```
def kotti_configure(settings):
    ...
    settings['kotti.use_workflow'] = u'kotti_yourplugin:workflow.zcml',
```

you'll get an error at startup time:
```
  File ".../python-dev/lib/python2.7/site-packages/kotti/__init__.py", line 257, in includeme
    if workflow.lower() not in FALSE_VALUES:
AttributeError: 'tuple' object has no attribute 'lower'
```
where workflow is:
```
(Pdb) workflow
(u'kotti_yourplugin:workflow.zcml',)
```

**Comment by davidemoro** [comment]
Workaround for affected versions: set "kotti.use_workflow" to a falsy value and load your custom workflow's zcml.

**Comment by sverbois** [comment]
You have to remove the comma in your code

    -    settings['kotti.use_workflow'] = u'kotti_yourplugin:workflow.zcml',
    +   settings['kotti.use_workflow'] = u'kotti_yourplugin:workflow.zcml'

**Comment by davidemoro** [comment]
Oh, what a stupid error ;)
Thank you!
