### ISSUE TITLE
No call to pyramid.paster.setup_logging for kotti-commands

### ISSUE THREAD

**Issue by lyrixderaven** [Kotti/Kotti#398]
The current *command* method in kotti/util.py does not call setup_logging, which results in a bunch of 

    No handlers could be found for logger "myapp.foobar"

errors. Since I don't know how to access the config file uri after the command has been initialized and called (of course I can access the content of the config file, but not which file it is), the call to *setup_loggin* would have to happen there. 

Is there a reason for this behaviour? It makes logging output from custom commands nigh impossible! A naive solution would be this:

```
def command(func, doc):
    args = docopt(doc)
    # establish config file uri
    config_uri = args['<config_uri>']
    pyramid_env = bootstrap(config_uri)
    # init logging
    from pyramid.paster import setup_logging
    setup_logging(config_uri)
    try:
        func(args)
    finally:
        pyramid_env['closer']()
    return 0
```

**Comment by dnouri** [comment]
Hey there!  Care to make a pull request with the proposed change?

**Comment by lyrixderaven** [comment]
cf. https://github.com/Kotti/Kotti/pull/400
