### ISSUE TITLE
Add target attribute to kotti.util.Link

### ISSUE THREAD

**Issue by davidemoro** [Kotti/Kotti#405]
This is not an issue.

In my Kotti application it would be good having a ``target`` attribute on ``kotti.util.Link``: https://github.com/Kotti/Kotti/blob/master/kotti/util.py#L175

This kind of change makes the menu links more generic and it seems it doesn't hurt.
Do you see any side effects?

**Comment by disko** [comment]
Not if we make ``target='_self'`` the default.

:+1:

**Comment by disko** [comment]
Implemented in #407
