### ISSUE TITLE
migration error on mysql

### ISSUE THREAD

**Issue by tonthon** [Kotti/Kotti#423]
When launching kotti-migrate app.in upgrade
```
ProgrammingError: (oursql.CollatedWarningsError) (None, 'query caused warnings', [(<class 'oursql.Warning'>, (u'Specified key was too long; max key length is 767 bytes', 1071L)), (<class 'oursql.Warning'>, (u'Specified key was too long; max key length is 767 bytes', 1071L))]) [SQL: u'CREATE INDEX ix_nodes_path ON nodes (path)']
```
The problem is In 1063d7178fa_add_node_path_column.py
the migration script adds the path column with an index:
```python
 19     op.add_column('nodes',                                                     
 20                   sa.Column('path', sa.Unicode(1000), index=True))
```

But Mysql doesn't support indexes larger than 767 bytes, it raises a waring. So the migration sscript fails.

Solution : 
```
kotti-migrate app.ini upgrade
# Comment the two lines in kotti/alembic/versions/1063d7178fa_add_node_path_column.py
kotti-migrate app.ini upgrade
kotti-migrate app.ini upgrade_all
```

Maybe kotti-migrate should ignore warnings

**Comment by disko** [comment]
Grmpfl – MySQL again :(

The correct solution would be to check for the dialect in the migration script and add the column without the index if it's ``mysql``.

We're doing that for new installations (https://github.com/Kotti/Kotti/blob/master/kotti/resources.py#L790), but obviously not in the migration step.
