### ISSUE TITLE
Migration error in path update 

### ISSUE THREAD

**Issue by tonthon** [Kotti/Kotti#424]
With a mysql database, the following error blocks the migration script (it's only a warning).
```
ProgrammingError: (oursql.CollatedWarningsError) (None, 'query caused warnings', [(<class 'oursql.Warning'>, (u"Truncated incorrect INTEGER value: '/'", 1292L))]) [SQL: u"update nodes set path = path || '/' where path not like '%/'"]
```
I'm not sure that the syntax of the sql statement is correct.
I didn't yet found a solution

**Comment by tonthon** [comment]
Commenting the line launching
```
update nodes set path = path || '/' where path not like '%/'
```
in kotti/alembic/versions/559ce6eb0949_update_node_path_column.py
of course allows to go one step further.

**Comment by disko** [comment]
This is similar to #423 in that it also only fails with MySQL :(

It seems that MySQL doesn't have the ``||`` operator for string concatenation, but uses a ``CONCAT`` function for this purpose (see https://dev.mysql.com/doc/refman/5.0/en/string-functions.html#function_concat).

Solution would be to check for the dialect in the migration script and execute a different SQL statement when it's ``mysql``.
