### ISSUE TITLE
Malformated links

### ISSUE THREAD

**Issue by Kebap** [Kotti/Kotti#431]
Hi, I found Kotti CMS a few days ago, it seems very interesting, however the standard functionality seems not to work 100% for me. I have installed Pyramid trough Paste.deploy & WSGIServer, with URL redirection, etc. like explained in [1]. Now I have installed Kotti and an example project "RanCos" on top [2]. However I noted strange behavior.

My Kotti currently resides at [3]. However, the correct address occasionally seems to get confused with [4]. For example, search results will link to [4] and not to [3] when referring to the Kotti Welcome page. I found the following source code at [5]

```html
    <dl id="search-results">
      <tal:repeat tal:repeat="result results">
        <dt class="search-result">
          <a href="${request.application_url}${result.path}">${result.title}</a>
```

Which will be rendered (wrongly) in my browser as [4]

```html
 <dt class="search-result">
          <a href="http://rancos.gienah.uberspace.de/fcgi-bin/RanCos/fcgi-bin/RanCos/">Welcome to Kotti</a>
```

How can this be prevented?

[1] http://blog.tsukiro.net/?p=409
[2] http://kotti.readthedocs.org/en/latest/first_steps/installation.html
[3] http://rancos.gienah.uberspace.de/fcgi-bin/RanCos/
[4] http://rancos.gienah.uberspace.de/fcgi-bin/RanCos/fcgi-bin/RanCos/
[5] https://github.com/Kotti/Kotti/blob/master/kotti/templates/view/search-results.pt

**Comment by disko** [comment]
You've probably discovered a bug in Kotti's path calculation which only occurs when Kotti runs under a subpath (``/fcgi-bin/RanCos`` in your case).  I assume most people (or even everyone else) run their Kotti apps on the root path of a (sub-) domain and therefore didn't encounter this yet.

Can you provide the contents of the ``path`` column in the ``nodes`` table?  I guess they all start with /fcgi-bin/RanCos``…

**Comment by Kebap** [comment]
Well, I, too, try to access my project on the root path of the subdomain [6]. It is only internally redirected to [3], not shown to the browser. This seems necessary due to hosting restrictions there. After clicking around in Kotti, it will be shown in the browser address bar, after all. So maybe you are right.

I will gladly provide more details for you to identify the possible bug. However, I did not follow the documentation completely, still wrangling with the tutorials. How would I access Kotti's ```nodes``` table?

[6] http://rancos.gienah.uberspace.de/

**Comment by davidemoro** [comment]
Hi @Kebap,

you can query the ``nodes``table (``path``column) if you are using a real database.

Or you can do it using the ``pshell`` command utility:
```
    $ pshell development.ini
    >>> from kotti.resources import Node
    >>> [item.path for item in Node.query.all()]
   ...
```

**Comment by Kebap** [comment]
When I try pshell, I get a strange error:

```
$ ../bin/pshell kotti_app.ini
Traceback (most recent call last):
  File "../bin/pshell", line 7, in <module>
    from pyramid.scripts.pshell import main
  File "/home/rancos/env/lib/python2.7/site-packages/pyramid/scripts/pshell.py", line 7, in <module>
    from pyramid.util import DottedNameResolver
  File "/home/rancos/env/lib/python2.7/site-packages/pyramid/util.py", line 6, in <module>
    from zope.interface import implementer
ImportError: No module named interface
```
Not sure what it means. The app works when opened via browser.

It seems like my Kotti uses the default SQLite, at least I see a Kotti.db file. So I started a SQLite database browser, and found the nodes table. I only have 2 elements, they are the default "About" and "Welcome to Kotti" with a respective path of ```/about/``` and ```/```.

So far not too uncommon.

**Comment by disko** [comment]
The traceback indicates that the ``pshell`` command doesn't use the same set of packages as your WSGI server.  I think I've seen errors like these on Ubuntu when the virtualenv wasn't created with the ``--no-site-packages`` option (might be wrong on this though, it's been a long time since I last used Ubuntu).

The values from ``nodes.path`` are just fine, not what I expected earlier.  As a consequence that means that ``request.application_url`` is ``http://rancos.gienah.uberspace.de/fcgi-bin/RanCos/fcgi-bin/RanCos`` from Kotti's / Pyramid's sight.  This is strange and most likely caused by an error in your frontend webserver configuration, for example in a rewrite rule or proxy config.

**Comment by Kebap** [comment]
I followed [1] to set-up Pyramid. That did use the ```--no-site-packages``` option for virtualenv. But I never worked with virtualenv before, so I might have done something wrong by accident. Also that tutorial did create a rewrite rule, towards the very bottom. Maybe that is a reason?

**Comment by disko** [comment]
Assuming this has been resolved.
