### ISSUE TITLE
Refactor add permission

### ISSUE THREAD

**Issue by davidemoro** [Kotti/Kotti#436]
This should be considerer an improvement ticket, not a bug.

Use case
========
You want to restrict content type "X" only to users with a particular role (eg: "roleX" assigned globally or with a local sharing). And "roleX" users should be able to manage "X" content types **only**.

Existing Kotti setup:
* in kotti **all** add views and ``add-dropdown`` view are protected with the "add" permission

Problems:
* if you want to display the ``add-dropdown`` menu for "roleX" users, they will be able to able to add also other content types with the existing setup

Possible "plonish" solution
====================
It would be better define a meta permission "add" and define specific content type permissions "add document", "add image", etc with fallbacks registered on the root ACL with default assignments ("add document" -> editor, etc).
The above specific permissions could be registered with a ``registerContentType`` or similar, while the add contents dropdown menu still continue to be protected by the generic "add" permission.

This way:
1- you create a new role "roleX"
2- you create a custom workflow with the "add" (meta permission) and the "add x" permissions (specific) assigned to the "roleX" role

Results:
* your local or global users with "roleX" will be able to manage "X" objects only (add, edit, review state, what do you want) without having to customize the `editor-bar.pt` template and/or ``add-dropdown``view.

This solution introduces: 
* complexity to the kotti setup but probably it is the most flexible setup if you want to accomplish to this kind of security requirements
* generators should be updated also
* a bit of pain, now or later all third party plugins should be converted

Ideas? If it doesn't fit the Kotti's design feel free to close this ticket.

**Comment by disko** [comment]
Seems rather complicated to me.

How about this:

- we add a ``add_permission`` attribute to ``kotti.resources.TypeInfo`` with a default value of ``add``
- the add views are protected with the permission from the respective type_info, e.g. ``permission="Document.type_info.add_permission``
- the add dropdown itself won't be protected at all, but will only be displayed if it contains at least one item; each item will be checked w.r.t. the required ``add_permission``

?

With these you should also be able to achieve the desired results, or do I miss something?

**Comment by davidemoro** [comment]
@disko: much better your proposal! :+1:

**Comment by davidemoro** [comment]
I've implemented @disko's proposal here:
https://github.com/davidemoro/Kotti/tree/dm-addperm

If should be ready for a PR.
PS: we should plan to change the ``view_config`` for other third party kotti plugins with custom resource (kotti_calendar, etc)

**Comment by tiberiuichim** [comment]
PR looks cool

@davidemoro any further work needed on this bit?
    
> the add dropdown itself won't be protected at all, but will only be displayed if it contains at least one item; each item will be checked w.r.t. the required add_permission

**Comment by davidemoro** [comment]
@tiberiuichim: no further work needed, I think. I removed the permission from the ``view_config`` and there were already a ``tal:condition`` in the add dropdown template. So if you cannot add any content, the add menu won't be displayed at all.

**Comment by davidemoro** [comment]
PR already merged and closed
