### ISSUE TITLE
Import error whilst attempting to use the 'browser' fixture from kotti.tests  

### ISSUE THREAD

**Issue by mgrbyte** [Kotti/Kotti#443]
I'm currently seeing this error:
from wsgi_intercept import add_wsgi_intercept, zope_testbrowser
ImportError: cannot import name zope_testbrowser

Project setup:

    pip install '.[dev,test]' -r https://raw.github.com/Kotti/Kotti/stable/requirements.txt

**Comment by disko** [comment]
On 4 Jul 2015, at 0:59, Matt Russell wrote:

> I'm currently seeing this error:
> from wsgi_intercept import add_wsgi_intercept, zope_testbrowser
> ImportError: cannot import name zope_testbrowser

I've seen that error when I tried to upgrade to a more recent version of 
wsgi_intercept (>= 0.6 IIRC).

Which version of wsgi_intercept is installed in your virtualenv (should 
be 0.5.1)

> Project setup:
>
>  pip install '.[dev,test]' -r 
> https://raw.github.com/Kotti/Kotti/stable/requirements.txt

I'm not sure what this does.  Can you please check if the error also 
occurs when you setup your project like this:

   pip install -r requirements.txt
   python setup.py dev


HTH,

Andreas

**Comment by mgrbyte** [comment]
@disko Sorry to take  to reply, been mega busy!
 > pip install '.[dev,test]' -er https://raw.github.com/Kotti/Kotti/stable/requirements.txt
This installs my project (defined in setup.py), when lists Kotti in its `install_requires` - 
it installs using pip, which does the right thing in regard to development requirements.

```bash
python setup.py dev 
```
 - this runs an alias defined in the setup.cfg that comes with Kotti:
```ini 
[aliases]
dev = develop easy_install Kotti[testing] Kotti[development]
```
We're developing a package which depends on Kotti, rather than developing Kotti itself,
so, we change the dev alias to:
 ```ini 
[aliases]
dev = develop easy_install mypackage[test] mypackage[dev]
```
, but that does not  do the right thing w/regard to development packages (at least for me, with latest pip), due to what `easy_install` does with .pth files.

FWIW, currently, using my current method or the method you describe does not pull wsgi.intercept  
:confused:

**Comment by disko** [comment]
On 8 Jul 2015, at 20:24, Matt Russell wrote:

> We're developing a package which depends on Kotti, rather than 
> developing Kotti itself,
> so, we change the dev alias to:
> ```ini
> [aliases]
> dev = develop easy_install mypackage[test] mypackage[dev]
> ```

This needs to be

```ini
[aliases]
dev = develop easy_install kotti[testing] kotti[development]
```

or maybe something like

```ini
[aliases]
dev = develop easy_install kotti[testing] kotti[development] 
mypackage[test]
```

if you have some additional ``extras_require={'test': …, }`` in your 
``setup.py``.

In any case you want your package's ``dev`` alias to also install 
**Kotti's** testing / development requirements.

**Comment by mgrbyte** [comment]
right, thanks!
