### ISSUE TITLE
SAWarning: Can't resolve label reference 'principals.name' when running tutorial

### ISSUE THREAD

**Issue by piotr-dobrogost** [Kotti/Kotti#445]
When running tutorial as described at http://kotti.readthedocs.org/en/latest/first_steps/tut-1.html I get the following warning:
`/home/piotr/projects/kotti/venv/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'principals.name'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))`

**Comment by mgrbyte** [comment]
@piotr-dobrogost This is to be expected - Kotti now depends on SQLAlchemy 1.0.6.
The behavior concerning SAWarnings is described in the [docs](http://docs.sqlalchemy.org/en/rel_1_0/changelog/migration_10.html#order-by-and-group-by-are-special-cases)

**Comment by disko** [comment]
Resolved in d2685d9edf3ce85301b543b286c6b5903b696e3e
