### ISSUE TITLE
Kotti scaffold for Pyramid should require kotti-tinymce package

### ISSUE THREAD

**Issue by piotr-dobrogost** [Kotti/Kotti#447]
`development.ini` from Kotti scaffold for Pyramid configures tinymc (`kotti.configurators = kotti_tinymce.kotti_configure`) yet `install_requires` in `setup.py` in the scaffold does not list `kotti-tinymce` package. As a result, after `pip install -e .` trying to run project ends with `ImportError: No module named kotti_tinymce`.

**Comment by disko** [comment]
``kotti_tinymce`` is not listed in ``install_requires``, because the ``Kotti`` package doesn't really depend on it.  It **is** contained in ``requirements.txt``, so following the official installation docs (``pip install -r requirements.txt``) doesn't lead to that error.

**Comment by piotr-dobrogost** [comment]
We are talking about project's (created based on scaffold) `setup.py` not Kotti's `setup.py` here. Such a project by including `kotti.configurators = kotti_tinymce.kotti_configure` in its configuration clearly requires `kotti_tinymce`. Either scaffold should not configure *kotti_tinymce* or if does it should list it as a requirement in its `setup.py`. I'm aware *kotti_tinymce* is present in `requirements.txt` but this doesn't make it unnecessary to declare it as a requirement in `setup.py` as this is top-level requirement which as you note is not required by Kotti itself.
