### ISSUE TITLE
Use of eval() in kotti.views.edit.__init__

### ISSUE THREAD

**Issue by tiberiuichim** [Kotti/Kotti#460]
There's an eval() call in `_eval_titles()`. What it does is construct i18n messages from the workflow state titles. For some reason, the state title come up as `u"_(u'Public')"`. For this reason the underscore _ needs to be available in that module, then we have a this line at the top:

```
from kotti.util import _  # why is this needed?  please explain!
```

And another one just to keep pyflakes happy about _, etc.

I guess the best way would be to somehow get the state titles as proper i18n messages so we don't have to eval them, but this needs to be investigated if feasible.

**Comment by tiberiuichim** [comment]
In the workflow definition (workflow.zcml), the state titles are defined as:

    <key name="title" value="_(u'Private')" />

I think we can change the ``_eval_titles`` to do the message construction using the state title as message id, and get rid of the embeded python code from the zcml file.

**Comment by disko** [comment]
Still need to verify, but I think ``title`` should be a TranslationString now (as of 1.3.0 / repoze.workflow 1.0b).

**Comment by tiberiuichim** [comment]
Can this can be closed now? I don't see the evil titles anymore in workflow.zcml

**Comment by tiberiuichim** [comment]
I've noticed the eval() call is now marked as deprecated, to be removed in Kotti 2.0. Closing this issue.
