### ISSUE TITLE
Database queries

### ISSUE THREAD

**Issue by umeboshi2** [Kotti/Kotti#478]
I have just been noticing lately that the database seems to be queried about every three seconds.  To make sure I didn't have any add-ons or extensions in the way, I created a new user and installed kotti from pip, ran the scaffolds, and setup the new project.

I was wondering why the database is being polled periodically, where this is in the code.

**Comment by umeboshi2** [comment]
Here is a bit more info.  I have been working on a rest api and frontend.  I started a temp project here: https://github.com/umeboshi2/ittok, which is a mangling of both kotti and alchemy scaffolds, and kotti is being used as a library.  This project doesn't experience the periodic database queries, however anytime I use just the kotti scaffolds, I experience this.  I went back to Kotti 1.0.0 and experienced the same behavior.

**Comment by umeboshi2** [comment]
While digging around looking for the problem, it seems to have stopped.

The behavior experienced was polling the principals on a three second interval.  It looked like two queries back-to-back each time.  It stopped unexpectedly while testing different versions of kotti.  Please label this as unreproducible in case it occurs again.

**Comment by disko** [comment]
That's totally strange.  Did you by any chance have a debugger session running, that might have caused that periodic queries?  TTBOMK there shouldn't be any queries outside of request handling ever in Kotti.

Closing for now, feel free to reopen…

**Comment by umeboshi2** [comment]
Strange is what I thought as well.  I've been using ```pdb.set_trace()``` to debug, and the queries were very annoying.  If this does pop up again, I would need to log sqlalchemy traces to find the caller, which I haven't had to do before.  I did poke around and try new virtualenvs, and even added a new user and used everything from pypi and only used sqlite database, and it still happened, although it didn't happen with regular alchemy scaffolds.  If it happens again, I'll reopen this.
