### ISSUE TITLE
LinkBase.selected should be checking against request.view_name

### ISSUE THREAD

**Issue by piotr-dobrogost** [Kotti/Kotti#489]
Right now `LinkBase.selected` checks against `request.url` and not `request.view_name` which it should be checking instead. As a result one can't use subpaths during traversal and when one sets default view in `view_content_default` the relevant link in editor-bar is not being selected when accessing url without view name specified like http://site.com/some/context/ (as opposed to http://site.com/some/context/@@default_view_name

**Comment by disko** [comment]
> Right now LinkBase.selected checks against request.url and not request.view_name which it should be checking instead. As a result one can't use subpaths during traversal 

Correct.  This should be fixed indeed.

> and when one sets default view in view_content_default the relevant link in edit bar is not being selected when accessing url without view name specified like http://site.com/some/context/ (as opposed to http://site.com/some/context/@@default_view_name

I still don't agree on that part.  You don't know if the selected view's name even has a corresponding Link in the the editor-bar (for me it most times does not).  Displaying "View" as active is always right though: you do "view" the context, regardless of its selected default view.  I don't want this to change.

**Comment by tiberiuichim** [comment]
I believe this can be closed now?

**Comment by disko** [comment]
Right! :)
