### ISSUE TITLE
Make "local groups" feature optional?

### ISSUE THREAD

**Issue by piotr-dobrogost** [Kotti/Kotti#499]
What do you think about making "local groups" feature optional?
In many cases it's not needed and slows down application.

**Comment by disko** [comment]
Could you elaborate on why / how it slows down an application when there are no local groups assigned and how you think it could be made optional?

IMO local groups are one of Kotti's most essential, powerful and unique features. I _always_ use them. Therefore I'd at most introduce an option to turn them off, but leaving them enabled by default.

Probably closely related: what I'd really like to do in future versions is to replace the Node._acl JSON list attribute with a proper relation in the DB that would allow to offload  some of the more expensive calculations to the DB.

/cc @dnouri

**Comment by castaf** [comment]
> Probably closely related: what I'd really like to do in future versions is to replace the Node._acl JSON list attribute with a proper relation in the DB that would allow to offload some of the more expensive calculations to the DB.


+1

**Comment by disko** [comment]
Closing this for now. Feel free to reopen if you think I missed your point.
