### ISSUE TITLE
DetachedInstanceError on 404 page

### ISSUE THREAD

**Issue by tiberiuichim** [Kotti/Kotti#511]
On a fresh checkout of Kotti, I get the attached error on going to http://localhost:5000/dsads

I have removed the pyramid_debugtoolbar from the pyramid.includes, to make the error simpler to understand.

My steps in reproducing:

```
git clone kotti
cd kotti
virtualenv .
bin/pip install -r requirements.txt
bin/pip uninstall Kotti
bin/pip install -e ".[testing,development]"
bin/py.test
bin/pserve development.ini
```

All tests passed, one skipped, when running Kotti tests.
[error.txt](https://github.com/Kotti/Kotti/files/559783/error.txt)

**Comment by tiberiuichim** [comment]
Trying in older versions: 

* OK in Kotti 1.0 (it has Pyramid's default 404 page)
* OK in Kotti 1.1 in default depot configuration (git checkout 1.1.5), still Pyramid default 404 page
* OK in Kotti 1.2, in default depot configuration, (git checkout 1.2.4), this time a kotti integrate 404 styled page

To test each tag I've used the same steps from above, in a fresh clone location, each time.

**Comment by tiberiuichim** [comment]
On the master version of Kotti, the error doesn't happed with the Anonymous user, only authenticated.

**Comment by motoz** [comment]
I'm seeing the same problem. Quick fix by adding `tal:on-error="string:"` to  the class definition in kotti/templates/nav.pt...
```
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse"
      id="navbar-view-collapse">
      <ul class="nav navbar-nav">
        <li tal:define="items [i for i in api.list_children(api.navigation_root) if i.in_navigation]"
            tal:repeat="item items"
            class="${api.inside(context, item) and 'active' or None}" tal:on-error="string:">
          <a href="${api.url(item)}" title="${item.description}">${item.title}</a>
        </li>
      </ul>
      <div tal:replace="api.render_template('kotti:templates/view/search.pt')" />
    </div>
```

**Comment by tiberiuichim** [comment]
But last change of nav.pt is in 13 May 2014, so something else must have changed in that time, something that changes how the sqlalchemy session interacts with objects out of the transaction scope (the pyramid_tm does a manager.abort() when it encounters an error, such as a HTTP exception in the view. I wonder if it wouldn't be more correct, in the pyramid_tm tween part, to do manager.doom() instead of manager.abort(), but I'm not an expert on the matter.

**Comment by motoz** [comment]
Yes of course. I have no idea what it's really about, but I needed a quick workaround and I thought I'd mention it just in case someone come here looking for that while waiting for a real fix.

**Comment by tiberiuichim** [comment]
The issues seems to be discussed here also: https://github.com/Pylons/pyramid_tm/issues/40

**Comment by tiberiuichim** [comment]
This has been worked around in #515 by simplifying the navbar to only show home link.
