### ISSUE TITLE
Maybe put the pyramid-debugtoolbar  into  requirements.txt?

### ISSUE THREAD

**Issue by beardad1975** [Kotti/Kotti#523]
I'm a kotti newbie . Just want to learn how Kotti worked.
When I installed Kotti in development mode and wanted to 
run it with pyramid-debugtoolbar. After installing mannually and
include it in the .ini file.  Everything seemed fine . But 
then I clicked the debugtoobar's button , I got a 
server internal error. And the console's error ouput was:

------
DetachedInstanceError: Instance <Document at 0xb1bced8c> is not bound to     a Session; attribute refresh operation cannot proceed
------

After  some  time trying .  I found out the cause was the version of 
debugtoolbar.  Latest version 3 was failed . Version 2.5 also. 
But version 2.4.2 worked.  But I could not find any info about 
the debugtoolbar's version in the requirements.txt.  So I just 
thought maybe  "pyramid-debugtoolbar==2.4.2" could included
in the requirements.  And someone like me could save some time
figuing out this problem.

By the way,  Thank you guys for this interesting project. Good Job!

**Comment by disko** [comment]
``pyramid-debugtoolbar`` is not required to run Kotti, so it doesn't belong into ``requirements.txt``. However, I just pinned it to ``<2.5`` in ``setup.py``, so that you get a working version when you run ``pip -e .[development]``.

Thanks for figuring out!

**Comment by beardad1975** [comment]
Nice Work! Thanks.
