### ISSUE TITLE
Session leakage

### ISSUE THREAD

**Issue by b4oshany** [Kotti/Kotti#526]
I built a system using Kotti that has preset users. However, upon logging in for the first time, those preset users are required to update their account information. For some unknown reason, there are cases where information for one user account is leaking over to another user account when registering.  I'm using nginx load balancing to manage two instances of Kotti and Pyramid beaker to manage the session.

**Comment by disko** [comment]
I've never experienced something like that myself.

How do you run those "two instances of Kotti"? As you're already using nginx, I'd highly recommend running Kotti under uWSGI and adjust the processes / threads configuration according to your needs. This works very well for us, for small applications as well as quite large ones. As long as a single machine is enough, I'd rather not touch load balancing through a frontend webserver.

**Comment by castaf** [comment]
Maybe it’s a problem about your Beaker’s backend configuration, what is it ?
