### ISSUE TITLE
py-bcrypt build fails on Windows 10

### ISSUE THREAD

**Issue by RichardProsser** [Kotti/Kotti#528]
I have attempted to install Kotti via the instructions given at http://kotti.readthedocs.io/en/latest/first_steps/installation.html but I get an error with py-bcrypt:

```
$ ./Scripts/pip install py-bcrypt                      
Collecting py-bcrypt                                    
  Using cached py-bcrypt-0.4.tar.gz                    
Building wheels for collected packages: py-bcrypt      
  Running setup.py bdist_wheel for py-bcrypt ... error  

```
followed by ...

```
 C:\Users\User\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -Ic:\user
games\kotti\kotti-env\PC /Tcbcrypt/blowfish.c /Fobuild\temp.win32-2.7\Release\bcrypt/blowfish.obj                                                                  
 blowfish.c                                                                                                                                                        
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2146: syntax error : missing ')' before identifier 'passlen'          
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2081: 'size_t' : name in formal parameter list illegal                
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2061: syntax error : identifier 'passlen'                              
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2059: syntax error : ';'                                              
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(86) : error C2059: syntax error : ','                                              
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(88) : error C2059: syntax error : ')'                                              
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2146: syntax error : missing ')' before identifier 'n'                
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2081: 'size_t' : name in formal parameter list illegal                
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2061: syntax error : identifier 'n'                                    
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2059: syntax error : ';'                                              
 c:\users\user\appdata\local\temp\pip-build-9lqins\py-bcrypt\bcrypt\pybc_blf.h(91) : error C2059: syntax error : ')'                                              
 error: command 'C:\\Users\\User\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2              
                                                                                                                                                                   
 ----------------------------------------                                                                                                                          
 Failed building wheel for py-bcrypt                                                                                                                              


```
There is a possible patch at https://code.google.com/archive/p/py-bcrypt/issues/18 and https://code.google.com/archive/p/py-bcrypt/issues/15 but I am not sure where the pybc_blf.h file can be found!

Further, I have searched the virtual env '*.py' files for references to 'bcyrpt' but I have not found any.

So:

    Can I ignore bcyrpt altogether (in which case it should be removed from the 'requirements.txt' file)?
    Can I use bcrypt instead? "This library should be compatible with py-bcrypt and it will run on Python 2.6+, 3.2+, and PyPy.".

**Comment by RichardProsser** [comment]
`pip install bcrypt` installs OK, apparently.

**Comment by disko** [comment]
> Can I ignore bcyrpt altogether (in which case it should be removed from the 'requirements.txt' file)?

No. Kotti uses it for password hashing.

> Can I use bcrypt instead? "This library should be compatible with py-bcrypt and it will run on Python 2.6+, 3.2+, and PyPy.".

Maybe.  If it **is** compatible with py-bcrypt, you should be able to manually install ``bcrypt`` in your virtualenv (``pip install bcrypt``), remove py-bcrypt from ``requirements.txt`` and / or ``setup.py`` and be fine.  If that's the case, you're more than welcome to open a pull request to replace the ``py-bcrypt`` dependency with ``bcrypt``.

**Comment by disko** [comment]
Closing this issue, as it's not directly related to Kotti.

As stated above, a PR / separate issue to replace the dependency with something that works on Windows will be highly appreciated!

**Comment by RichardProsser** [comment]
I hope that is what you meant by a 'separate issue'. I have never done a PR before; I may be willing to do so but I don't have a lot of time to spare.

**Comment by disko** [comment]
No worries, we're willing to help!

For such simple 2-line changes, it might be sufficient to 

  1. fork Kotti
  2. edit the files through the github website (on your fork)
  3. start a new pull request

If you're new to all of this, github has some good docs: https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/

**Comment by Mrutyunjay01** [comment]
> `pip install bcrypt` installs OK, apparently.

Nope. It didn't work in my case. I tried installing lrutils via pip3 and I got the same error. Then I proceeded through the py_bcrypt error and hence installed bcrypt too. Still, I am getting the same error as previous.
