### ISSUE TITLE
pip install -r https://raw.github.com/Kotti/Kotti/stable/requirements.txt fails on Windows.

### ISSUE THREAD

**Issue by RichardProsser** [Kotti/Kotti#529]
Further to https://github.com/Kotti/Kotti/issues/528, py-bcrypt is also referenced by https://raw.githubusercontent.com/Kotti/Kotti/testing/requirements.txt, which in turn is 'pulled' by https://github.com/Kotti/kotti_image/blob/master/requirements.txt, so simply replacing py-bcrypt by bcrypt in https://github.com/Kotti/Kotti/blob/master/requirements.txt will not work IMO.

I also had a problem with lxml, which can be fixed by placing it before lingua in master/requirements.txt I believe.

FYI, I am using Windows 10 version 1607, and MING64 via ConEmu. Microsoft\Visual C++ for Python 9.0 is installed.

**Comment by disko** [comment]
``testing`` is the release branch for all releases (alpha, beta, final). It gets updated for every release. ``production`` is the release branch for all final releases (**not** alpha or beta).

``kotti_image``'s ``requirements.txt`` is not used during the installation of Kotti, but only when running the tests for ``kotti_image``.

Therefore updating ``requirements.txt`` and ``setup.py`` on the ``kotti/master`` branch will be sufficient. 

The order in ``requirements.txt`` shouldn't matter at all.  So unless you're absolutely sure that it does make a difference (try to reproduce again on a clean virtualenv), I'd like to keep ``requirements.txt`` sorted alphabetically.  Unfortunately Travis CI doesn't support running the test suite on Windows :(

**Comment by disko** [comment]
Closing for now.
