### ISSUE TITLE
Missing kotti_tinymce in requirements

### ISSUE THREAD

**Issue by davidemoro** [Kotti/Kotti#552]
After pip installing the requirements.txt as suggested by the documentation in the installation guide, you'll get an import error launching ``pserve app.ini``:
* kotti_tinymce import error
* pytest import error (I think this is an error because there is no need to install pytest for a production site)

Tested with:
* https://raw.githubusercontent.com/Kotti/Kotti/2.0.0b2/requirements.txt

**Comment by disko** [comment]
Thanks for reporting!

``kotti_tinymce`` is optional in Kotti >= 2.0
