### ISSUE TITLE
Documentations out of date on readthedocs

### ISSUE THREAD

**Issue by tanhaa** [Kotti/Kotti#554]
Just a quick note to let you guys know that the documentation on readthedocs still says no support for python3, whereas according to PR #550 the python2 support has been dropped.

**Comment by disko** [comment]
Thanks for reporting!

Actually the docs are up to date, but RTD is setup to display the docs for the latest *stable* version, which currently is 1.3.2.

As no bugs have been reported for 2.0.0b2, we should probably release 2.0.0 final real soon now (tm).
