### ISSUE TITLE
Need help to implement public user registration  

### ISSUE THREAD

**Issue by geohuz** [Kotti/Kotti#558]
I'm going to use kotti as a public website which allows user to download files from site. And I need to implement a user registration form so they can register themself into the site. Any suggestion how to do it?

**Comment by disko** [comment]
You just need to set 

``kotti.register`` to ``True``

in your ``.ini`` file.

You can also set ``kotti.register.group`` and/or ``kotti.register.role`` to assign newly registered users to a default group or role.

**Comment by disko** [comment]
Sorry for the late reply. Github was "broken" (at least for me) and didn't allow comments until now.
