### ISSUE TITLE
Need help to implement public user registration form 

### ISSUE THREAD

**Issue by geohuz** [Kotti/Kotti#559]
How can I implement a user registration form on the site? We only have login now I need register functionality.

**Comment by castaf** [comment]
There is already a view for this : https://github.com/Kotti/Kotti/blob/07f8973843bd5c776ee92e02bb43765b2df7b8be/kotti/views/login.py#L77 <https://github.com/Kotti/Kotti/blob/07f8973843bd5c776ee92e02bb43765b2df7b8be/kotti/views/login.py#L77>.

And in your paste config, you have to set : kotti.register = True.
