### ISSUE TITLE
"NotImplementedError: Can't perform this operation for unregistered loader type" for kotti:locale/

### ISSUE THREAD

**Issue by davidemoro** [Kotti/Kotti#563]
Don't know if it is a kotti specific compatibility issue (full logs here https://pastebin.com/i6nPDH3Y):
```
-> return self.pkg_resources.resource_isdir(self.pkg_name, self.path)
  (Pdb) self.pkg_name
  'kotti'
  (Pdb) self.path
  'locale/'
  (Pdb) self.pkg_resources.resource_isdir(self.pkg_name, self.path)
  *** NotImplementedError: Can't perform this operation for unregistered loader type
```

Requirements:
* https://pastebin.com/nawCcEbj

Python version:
* 3.6.8

Anyone already saw a similar failure in kotti? Any hint about some compatibility issues in my dependencies versions?

Thanks in advance

**Comment by disko** [comment]
I've never seen this. How do you trigger it?

**Comment by davidemoro** [comment]
I'm just running tests with tox/pytest for a Kotti application (I am not the one who is calling this API).

As you can see I got this problem only invoking the pyramid API for the kotti package:
```
(Pdb) resolver.resolve('bddplay:locale/').isdir() 
True
(Pdb) resolver.resolve('kotti:locale/').isdir()  
*** NotImplementedError: Can't perform this operation for unregistered loader type
```

**Comment by davidemoro** [comment]
I'm closing because this is not a kotti issue, it seems more a specific pytest issue. Sorry for the noise!

For other people with the same problem, it seems that there is a wrong loader:
```
(Pdb) _find_adapter(_provider_factories, loader)(module)
<pkg_resources.DefaultProvider object at 0x7ff7229d7668>
(Pdb) module
<module 'bddplay' from '/home/davide/workspaces/bddplay/src/bddplay/.tox/py36/lib/python3.6/site-packages/bddplay/__init__.py'>
(Pdb) loader                                            
<_frozen_importlib_external.SourceFileLoader object at 0x7ff725a77160>
(Pdb) module
<module 'bddplay' from '/home/davide/workspaces/bddplay/src/bddplay/.tox/py36/lib/python3.6/site-packages/bddplay/__init__.py'>
...
(Pdb) module
<module 'kotti' from '/home/davide/workspaces/bddplay/src/bddplay/.tox/py36/lib/python3.6/site-packages/kotti/__init__.py'>
(Pdb) loader
<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x7ff728e8b470>
(Pdb) _find_adapter(_provider_factories, loader)(module)
<pkg_resources.NullProvider object at 0x7ff7229d7390>
```

**Comment by davidemoro** [comment]
Confirmed: this is not a Kotti issue. Solved downgrading pytest:
```
-pytest==5.0.1
+pytest==4.6.2
```

**Comment by disko** [comment]
Great! Would you mind pinning pytest in ``tests_require`` in ``setup.py``, maybe with a comment pointing to this issue?

**Comment by davidemoro** [comment]
Hi @disko, sorry for the delayed response.

Do you mean inside the Kotti codebase?

**Comment by openbrian** [comment]
I see this issue when running automated tests.

**Comment by openbrian** [comment]
@disko I suggest you re-open this issue, as it's a major blocker for future development.  This is probably why there's no passing build in Travis for 10 months.  (The other issue about SQLAlchemy is not what started the tests to fail.)

**Comment by disko** [comment]
Thanks for bringing this up again.

This seems to be an issue with ``pytest>=5``. You can ``pip install "pytest<5"`` or run ``pip install -e ".[testing]"`` against the current master again.

**Comment by openbrian** [comment]
I'm on it.

**Comment by openbrian** [comment]
The downgrade of pytest from 5 to 4 alone does not solve this issue.  I'll now test #564 alone without the pytest downgrade.

**Comment by openbrian** [comment]
Yes this solves the "unregistered loader type" issue.
