### ISSUE TITLE
Kotti at PyPi needs to be synced with github latest version

### ISSUE THREAD

**Issue by sydoluciani** [Kotti/Kotti#573]
starting Kotti after initial installation throws below error:
from zope.sqlalchemy import ZopeTransactionExtension
ImportError: cannot import name 'ZopeTransactionExtension'

The fix included in github file but not included in pip repository.

**Comment by disko** [comment]
Thanks for the reminder. I need to cut a new release containing that change.

Won't be this week though, probably beginning of the next week.

**Comment by sydoluciani** [comment]
@disko any update on this issue ?
 
Still the same error on starting Kotti after fresh installation :
    from zope.sqlalchemy import ZopeTransactionExtension
ImportError: cannot import name 'ZopeTransactionExtension' from 'zope.sqlalchemy'

**Comment by disko** [comment]
Forgot to close the issue when it was resolved.
