### ISSUE TITLE
Node.__getitem__ needs to become simpler

### ISSUE THREAD

**Issue by dnouri** [Kotti/Kotti#75]
`Node.__getitem__` currently accepts a tuple as a key.  It does this to try and optimize the case where a subitem is requested.  It also goes to great lengths to try and optimize for when `self._children` is already loaded.

Propose to drop the feature where we can pass a tuple to `__getitem__` like `root['level1', 'level2']`.  This seems like a bad idea.  We could provide a separate public `traverse()` function that does this, if we decide that this is at all useful.

The optimization via `self._children` should probably go away, too.  An more workable alternative would be to use the request to cache subsequent access to the same child object.  A mix-in that does this could look like this:

```python
from kotti.util import request_container

class CachingContainerMixin(object):
    def _get_cache_container(self):
        id = vars(self).get('id')
        cont = request_container()
        if id is None or cont is None:
            return {}

        key = (CachingContainerMixin, self.id)
        return cont.setdefault(key, {})

    def __setitem__(self, key, value):
        self._get_cache_container().clear()
        return super(CachingContainerMixin, self).__setitem__(key, value)

    def __delitem__(self, key):
        self._get_cache_container().clear()
        return super(CachingContainerMixin, self).__delitem__(key)

    def __getitem__(self, key):
        cache_key = tuple(key) if isinstance(key, list) else key
        cached_value = self._get_cache_container().get(cache_key)
        if cached_value is not None:
            return cached_value
        value = super(CachingContainerMixin, self).__getitem__(key)
        self._get_cache_container()[cache_key] = value
        return value
```

**Comment by disko** [comment]
Obsolete with the custom traverser in 1.3.0. You can now use all everything from ``pyramid.traversal``, including the ``traverse`` function.
